#!/usr/bin/env node

var functions = require('./index');
var sharedWords = functions.sharedWords;

var program = require('commander');
var fs = require('fs');

program
  .version('0.1.0')
  .option('-n --number', 'Just show number of words')
  .parse(process.argv);

var files = program.args;
var file1 = files[0];
var file2 = files[1];

if (files.length !== 2) {
  console.log('You need to give two files.');
  process.exit(1);
}

var allContents = [];

var wordReader = function(err, contents) {
  allContents.push(contents.split(' '));
  if (allContents.length === 2) {
    displayCommonWords(allContents[0], allContents[1]);
  }
};

fs.readFile(file1, { encoding: 'utf-8' }, wordReader);
fs.readFile(file2, { encoding: 'utf-8' }, wordReader);

var displayCommonWords = function(words1, words2) {
  var common = sharedWords(words1, words2);
  common.forEach(function(word) {
    console.log(word);
  });
};