#!/usr/bin/env node

var functions = require('./index');
var sharedWords = functions.sharedWords;

var program = require('commander');
var fs = require('fs');

program
  .version('0.1.0')
  .option('-n --number', 'Just show number of words')
  .parse(process.argv);

var files = program.args;
var file1 = files[0];
var file2 = files[1];

if (files.length !== 2) {
  console.log('You need to give two files.');
  process.exit(1);
}

var numberOfFilesRead = 0;
var words1;
var words2;

fs.readFile(file1, { encoding: 'utf-8' }, function(err, contents1) {
  words1 = contents1.split(' ');
  numberOfFilesRead = numberOfFilesRead + 1;
  if (numberOfFilesRead === 2) {
    displayCommonWords();
  }
});

fs.readFile(file2, { encoding: 'utf-8' }, function(err, contents2) {
  words2 = contents2.split(' ');
  numberOfFilesRead = numberOfFilesRead + 1;
  if (numberOfFilesRead === 2) {
    displayCommonWords();
  }
});

var displayCommonWords = function() {
  var common = sharedWords(words1, words2);
  common.forEach(function(word) {
    console.log(word);
  });
};